/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visuel;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Guillet
 */
public class ApercuDocAnnexeImage extends javax.swing.JPanel {

    /**
     * Creates new form ApercuDocAnnexeImage
     */
    public ApercuDocAnnexeImage() {
        initComponents();
    }

    public ApercuDocAnnexeImage(ImageIcon fichierDocAnnexe) {
        initComponents();
        zoneImage.setIcon(fichierDocAnnexe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoneImage = new javax.swing.JButton();

        zoneImage.setRolloverEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zoneImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zoneImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton zoneImage;
    // End of variables declaration//GEN-END:variables
}
