/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FenAjoutLien.java
 *
 * Created on 11 févr. 2012, 19:43:27
 */
package visuel;

/**
 *
 * @author jean
 */
public class FenAjoutLien extends javax.swing.JPanel {

    /** Creates new form FenAjoutLien */
    public FenAjoutLien() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
