/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visuel;

import arbreGene.DocAnnexeTxt;

/**
 *
 * @author Guillet
 */
public class PopupDocAnnexeTxt extends javax.swing.JDialog {

    /**
     * Creates new form PopupDocAnnexeTxt
     */
    public PopupDocAnnexeTxt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public PopupDocAnnexeTxt(DocAnnexeTxt docIni, PopupListeDocAnnexe parent) {
        super();
        initComponents();
        this.parent = parent;
        if (docIni.getTitre() != null) {
            champTitre.setText(docIni.getTitre());
        }
        if (docIni.getDoc() != null) {
            zoneTxt.setText(docIni.getDoc());
        }
        
        crea = (docIni.getTitre() == null & docIni.getDoc() == null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauTitre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        champTitre = new javax.swing.JTextField();
        boutonOk = new javax.swing.JButton();
        boutonAnnu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        zoneTxt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jLabel1.setText("Titre : ");

        boutonOk.setText("Ok");
        boutonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOkActionPerformed(evt);
            }
        });

        boutonAnnu.setText("Annuler");
        boutonAnnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAnnuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneauTitreLayout = new javax.swing.GroupLayout(panneauTitre);
        panneauTitre.setLayout(panneauTitreLayout);
        panneauTitreLayout.setHorizontalGroup(
            panneauTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauTitreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(champTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(boutonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutonAnnu)
                .addContainerGap())
        );
        panneauTitreLayout.setVerticalGroup(
            panneauTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauTitreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panneauTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(champTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonOk)
                    .addComponent(boutonAnnu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        zoneTxt.setColumns(20);
        zoneTxt.setRows(5);
        jScrollPane1.setViewportView(zoneTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panneauTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panneauTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOkActionPerformed
        DocAnnexeTxt doc = new DocAnnexeTxt();
        doc.setTitre(champTitre.getText());
        doc.setDoc(zoneTxt.getText());
        if (!crea)
        {
            parent.Supprime();
        }
        parent.Ajout(doc);
        dispose();
    }//GEN-LAST:event_boutonOkActionPerformed

    private void boutonAnnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnuActionPerformed
        dispose();
    }//GEN-LAST:event_boutonAnnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupDocAnnexeTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupDocAnnexeTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupDocAnnexeTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupDocAnnexeTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopupDocAnnexeTxt dialog = new PopupDocAnnexeTxt(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnu;
    private javax.swing.JButton boutonOk;
    private javax.swing.JTextField champTitre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panneauTitre;
    private javax.swing.JTextArea zoneTxt;
    // End of variables declaration//GEN-END:variables
    private PopupListeDocAnnexe parent;
    private boolean crea = true;
}
