/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visuel;

import arbreGene.Arbre;
import arbreGene.FPersonne;
import arbreGene.ModelTabLien;

/**
 *
 * @author Guillet
 */
public class popupListeLiens extends javax.swing.JDialog {

    public popupListeLiens() {
        super();
        initComponents();
    }

    /**
     * Creates new form popupListeLiens
     */
    public popupListeLiens(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public popupListeLiens(FPersonne fp, Arbre ar) {
        super();
        initComponents();
        fPersSauv = fp;
        fPers = new FPersonne(fp);
        this.setTitle("Liste des liens de " + fp.getIdentite().getPrenom() + " " + fp.getIdentite().getNom());
        
        if (fp.getListeTypeLiens() != null) {
            mod.creaData(fp.getListeTypeLiens().size());
            for (int ind = 0; ind < fp.getListeTypeLiens().size(); ind++)
            {
                mod.addData(fp.getListeTypeLiens().get(ind), ar.get(fp.getListeTypeLiens().get(ind).getAvecPersonne()).getIdentite());
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tableLien = new javax.swing.JTable();
        boutonOK = new javax.swing.JButton();
        boutonAnnu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tableLien.setModel(mod);
        jScrollPane1.setViewportView(tableLien);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 1;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        boutonOK.setText("Ok");
        boutonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(boutonOK, gridBagConstraints);

        boutonAnnu.setText("Annuler");
        boutonAnnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAnnuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        getContentPane().add(boutonAnnu, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOKActionPerformed
        fPersSauv = fPers;
        dispose();
    }//GEN-LAST:event_boutonOKActionPerformed

    private void boutonAnnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnuActionPerformed
        dispose();
    }//GEN-LAST:event_boutonAnnuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popupListeLiens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popupListeLiens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popupListeLiens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popupListeLiens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                popupListeLiens dialog = new popupListeLiens(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnu;
    private javax.swing.JButton boutonOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLien;
    // End of variables declaration//GEN-END:variables
    //variables perso
    private FPersonne fPers;
    private FPersonne fPersSauv;
    private ModelTabLien mod = new ModelTabLien();
}
