/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visuel;

import arbreGene.DocAnnexeImage;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Guillet
 */
public class PopupDocAnnexeImage extends javax.swing.JDialog {
    
    /**
     * Creates new form PopupDocAnnexeImage
     */
    public PopupDocAnnexeImage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public PopupDocAnnexeImage(DocAnnexeImage doc) {
        super();
        initComponents();
        champTitre.setText(doc.getTitre());
        imaTemp = doc.getDoc();
        Image ima2 = imaTemp.getImage().getScaledInstance(zoneImage.getWidth(), zoneImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
        zoneImage.setIcon(new ImageIcon(ima2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zoneImage = new javax.swing.JButton();
        panneauTitre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        champTitre = new javax.swing.JTextField();
        boutonOk = new javax.swing.JButton();
        boutonAnnu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        zoneImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneImageActionPerformed(evt);
            }
        });

        jLabel1.setText("Titre : ");

        boutonOk.setText("Ok");

        boutonAnnu.setText("Annuler");

        javax.swing.GroupLayout panneauTitreLayout = new javax.swing.GroupLayout(panneauTitre);
        panneauTitre.setLayout(panneauTitreLayout);
        panneauTitreLayout.setHorizontalGroup(
            panneauTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauTitreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(champTitre, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(boutonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutonAnnu)
                .addContainerGap())
        );
        panneauTitreLayout.setVerticalGroup(
            panneauTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauTitreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panneauTitreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(champTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonOk)
                    .addComponent(boutonAnnu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zoneImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panneauTitre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panneauTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zoneImage, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zoneImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneImageActionPerformed
                //ouverture boite de dialogue recherche fichier
        final JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File(".")); //NOI18N
        //In response to a button click:
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "FICHIER IMAGE", "jgp", "JPG"); //NOI18N
        fc.setFileFilter(filter);

        int returnVal = fc.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String fichierIma = fc.getSelectedFile().getPath();
            imaTemp = new ImageIcon(fichierIma);
            Image ima2 = imaTemp.getImage().getScaledInstance(zoneImage.getWidth(), zoneImage.getHeight(), java.awt.Image.SCALE_SMOOTH);
            zoneImage.setIcon(new ImageIcon(ima2));
        } else {
            System.out.println(java.util.ResourceBundle.getBundle("visuel/Bundle").getString("FICHIER NON SELECTIONNE"));
        }
    }//GEN-LAST:event_zoneImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupDocAnnexeImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupDocAnnexeImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupDocAnnexeImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupDocAnnexeImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PopupDocAnnexeImage dialog = new PopupDocAnnexeImage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAnnu;
    private javax.swing.JButton boutonOk;
    private javax.swing.JTextField champTitre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panneauTitre;
    private javax.swing.JButton zoneImage;
    // End of variables declaration//GEN-END:variables
    private ImageIcon imaTemp;
}
