/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visuel;

import arbreGene.Arbre;
import arbreGene.FPersonne;
import arbreGene.ModelTabLien;

/**
 *
 * @author Guillet
 */
public class PopupListeLien extends javax.swing.JDialog {

    public PopupListeLien() {
        super();
        initComponents();
    }

    /**
     * Creates new form PopupListeLien
     */
    public PopupListeLien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public PopupListeLien(FPersonne fp, Arbre ar) {
        super();
        initComponents();
        fPersSauv = fp;
        fPers = new FPersonne(fp);
        this.setTitle("Liste des liens de " + fp.getIdentite().getPrenom() + " " + fp.getIdentite().getNom());
        
        if (fp.getListeTypeLiens() != null) {
            mod.creaData(fp.getListeTypeLiens().size());
            for (int ind = 0; ind < fp.getListeTypeLiens().size(); ind++)
            {
                mod.addData(fp.getListeTypeLiens().get(ind), ar.get(fp.getListeTypeLiens().get(ind).getAvecPersonne()).getIdentite());
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonOKActionPerformed
        fPersSauv = fPers;
        dispose();
    }//GEN-LAST:event_boutonOKActionPerformed

    private void boutonAnnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAnnuActionPerformed
        dispose();
    }//GEN-LAST:event_boutonAnnuActionPerformed

    private void boutonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAjoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonAjoutActionPerformed

    private void boutonModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonModifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonModifActionPerformed

    private void boutonSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonSuppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupListeLien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupListeLien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupListeLien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupListeLien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PopupListeLien dialog = new PopupListeLien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    //variables perso
    private FPersonne fPers;
    private FPersonne fPersSauv;
    private ModelTabLien mod = new ModelTabLien();
}
